### ISSUE TITLE
Not getting callback for success function after submitting the OTP

### ISSUE THREAD

**Issue by jimkaler** [xendit/xendit-js-node#7] opened 2018-12-06 09:38 UTC
Hi, I am using this library in ReactJS project and I've implemented it successfully, but in Review condition after submitting the OTP it is not calling the handler function again, which have success function as well. 

Basically I am unable to know if payment has been verified or not?

 import React, { Component } from 'react'
import Xendit from 'xendit-js-node';
import Modal from 'react-responsive-modal';

const EX_API_KEY = 'MY-API-KEY';
export default class componentName extends Component {
    state = {
        showModal:false,
    }
    componentWillMount(){
        Xendit.setPublishableKey(EX_API_KEY);
        var tokenData = this.getTokenData();
        Xendit.card.createToken(tokenData, this.xenditResponseHandler.bind(this));
    }
    displaySuccess (creditCardToken) {
        var requestData = Object.assign({}, this.getTokenData(), this.getFraudData());

        if (this.state.should_use_meta) {
            requestData["meta_enabled"] = true;
        } else {
            requestData["meta_enabled"] = false;
        }

        alert(
            'RESPONSE: \n' +
            JSON.stringify(creditCardToken, null, 4) +
            '\n\n' +
            'Request Data: \n' +
            JSON.stringify(requestData, null, 4)
        );
    }

    displayError (err) {
        var requestData = Object.assign({}, this.getTokenData(), this.getFraudData());

        if (this.state.should_use_meta) {
            requestData["meta_enabled"] = true;
        } else {
            requestData["meta_enabled"] = false;
        }

        alert(
            'Error: \n' +
            JSON.stringify(err, null, 4) +
            '\n\n' +
            'Request Data: \n' +
            JSON.stringify(requestData, null, 4)
        );
    };
    
    getFraudData () {
        return JSON.parse(this.state.meta_json);
    }

    getTokenData () {
        return {        
            "amount": "75000",        
            "card_number": "4000000000000002",
            "card_exp_month": "12",        
            "card_exp_year": "2018",
            "card_cvn": "123",
            "is_multiple_use": false,
            "should_authenticate": true,
        };
    }
    

    xenditResponseHandler (err, creditCardToken) {
        
        if (err) {
            return this.displayError(err);
        }
        if (creditCardToken.status === 'APPROVED' || creditCardToken.status === 'VERIFIED') {
            this.displaySuccess(creditCardToken);
            console.log("VERIFIED",creditCardToken.status);
            
        } 
        else if (creditCardToken.status === 'IN_REVIEW') {
            this.setState({ 
                redirectedUrl: creditCardToken.payer_authentication_url,
                showModal:true
             })
             window.open(creditCardToken.payer_authentication_url, 'sample-inline-frame');
        }
         else if (creditCardToken.status === 'FAILED') {
           this.displayError(creditCardToken)
        }
    }

    onCloseModal = () => {
        this.setState({ showModal: false });
      };
  render() {
    return (
      <div>
         <Modal 
            open={this.state.showModal} 
            closeOnEsc={false} 
            showCloseIcon={true} 
            closeOnOverlayClick={false} 
            onClose={this.onCloseModal} 
            blockScroll={true}
            center>
                <iframe title="Of" height="450" width="550" id="sample-inline-frame" name="sample-inline-frame"> </iframe>
         </Modal>
      </div>
    )
  }
}
The Popup of Iframe is getting submitted successfully but not calling the displaySuccess() function again.

**Comment by hakiemaul** [comment] 2018-12-06 15:54
@jimkaler for implementation using ReactJS, have you tried using this our Xendit.js library instead? Available via CDN in this URL https://js.xendit.co/v1/xendit.min.js

To use it, simply put it in the head section, and the `Xendit` object should be available inside of your component, so it should not disrupt your current implementation flow.

This library is developed to be used with React Native's WebView, so I think it's a possibility it might not behave as intended if used using iframe.

**Comment by jimmy818** [comment] 2018-12-07 04:38
@hakiemaul Thanks for the reply. I've just put cdn in global header and won't be able to access Xendit object in my components. Do you think it will work in ReactJS?

**Comment by jimmy818** [comment] 2018-12-07 07:36
Yes! it works. Thanks @hakiemaul.

**Comment by zxr90** [comment] 2019-05-13 07:31
@hakiemaul Would you consider posting an example implementation of using react with xendit.js? Thanks

**Comment by hakiemaul** [comment] 2019-05-15 04:23
@zxr90 we will post implementation example for React Native using this library in the next 2 weeks.

For implementation with react and xendit.js should be similar with how our tokenization test site works https://js.xendit.co/test_tokenize.html

**Comment by hakiemaul** [comment] 2019-05-15 04:23
Closing this issue because original concern has been addressed

**Closed** 2019-05-15 04:32 UTC
